pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        // osmdroid tiles / library
        maven { url "https://repo1.maven.org/maven2" }
    }
}

rootProject.name = "FakeGPS"
include ':app'
